version = '2'

[linters]
enable = [
  'misspell',
  'revive'
]

[linters.settings]
[linters.settings.govet]
enable = [
  'shadow'
]
disable = [
  'composites'
]

[linters.settings.misspell]
locale = 'US'

[linters.exclusions]
generated = 'lax'
presets = [
  'comments',
  'common-false-positives',
  'legacy',
  'std-error-handling'
]
paths = [
  'third_party$',
  'builtin$',
  'examples$'
]

[[linters.exclusions.rules]]
path = '(.+)\.go$'
text = 'declaration of "(err|ctx)" shadows declaration at'

[issues]
max-same-issues = 0

[formatters]
enable = [
  'gofmt',
  'goimports'
]

[formatters.settings]
[formatters.settings.goimports]
local-prefixes = [
  'github.com/cloudchacho/hedwig-go'
]

[formatters.exclusions]
generated = 'lax'
paths = [
  'third_party$',
  'builtin$',
  'examples$'
]
