// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v5.29.5
// source: protobuf_bad.proto

package internal

import (
	_ "github.com/cloudchacho/hedwig-go/protobuf"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// error: bad name and no message_type option
type DeviceCreated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Foobar *int32 `protobuf:"varint,1,req,name=foobar" json:"foobar,omitempty"`
}

func (x *DeviceCreated) Reset() {
	*x = DeviceCreated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_bad_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCreated) ProtoMessage() {}

func (x *DeviceCreated) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_bad_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCreated.ProtoReflect.Descriptor instead.
func (*DeviceCreated) Descriptor() ([]byte, []int) {
	return file_protobuf_bad_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceCreated) GetFoobar() int32 {
	if x != nil && x.Foobar != nil {
		return *x.Foobar
	}
	return 0
}

// error: bad name and no major_version option
type DeviceCreatedNew struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Foobar *int32 `protobuf:"varint,1,req,name=foobar" json:"foobar,omitempty"`
}

func (x *DeviceCreatedNew) Reset() {
	*x = DeviceCreatedNew{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_bad_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceCreatedNew) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCreatedNew) ProtoMessage() {}

func (x *DeviceCreatedNew) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_bad_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCreatedNew.ProtoReflect.Descriptor instead.
func (*DeviceCreatedNew) Descriptor() ([]byte, []int) {
	return file_protobuf_bad_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceCreatedNew) GetFoobar() int32 {
	if x != nil && x.Foobar != nil {
		return *x.Foobar
	}
	return 0
}

// error: major version mismatch
type TripCreatedV4 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId *string `protobuf:"bytes,1,req,name=device_id,json=deviceId" json:"device_id,omitempty"`
}

func (x *TripCreatedV4) Reset() {
	*x = TripCreatedV4{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_bad_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TripCreatedV4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripCreatedV4) ProtoMessage() {}

func (x *TripCreatedV4) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_bad_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripCreatedV4.ProtoReflect.Descriptor instead.
func (*TripCreatedV4) Descriptor() ([]byte, []int) {
	return file_protobuf_bad_proto_rawDescGZIP(), []int{2}
}

func (x *TripCreatedV4) GetDeviceId() string {
	if x != nil && x.DeviceId != nil {
		return *x.DeviceId
	}
	return ""
}

// error: duplicate message type / major version
type TripCreatedV2New struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId *string `protobuf:"bytes,1,req,name=device_id,json=deviceId" json:"device_id,omitempty"`
}

func (x *TripCreatedV2New) Reset() {
	*x = TripCreatedV2New{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_bad_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TripCreatedV2New) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripCreatedV2New) ProtoMessage() {}

func (x *TripCreatedV2New) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_bad_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripCreatedV2New.ProtoReflect.Descriptor instead.
func (*TripCreatedV2New) Descriptor() ([]byte, []int) {
	return file_protobuf_bad_proto_rawDescGZIP(), []int{3}
}

func (x *TripCreatedV2New) GetDeviceId() string {
	if x != nil && x.DeviceId != nil {
		return *x.DeviceId
	}
	return ""
}

var File_protobuf_bad_proto protoreflect.FileDescriptor

var file_protobuf_bad_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x62, 0x61, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x68, 0x65, 0x64, 0x77, 0x69, 0x67, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x2f, 0x0a, 0x0d, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6f, 0x6f, 0x62, 0x61, 0x72, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x05, 0x52, 0x06, 0x66, 0x6f, 0x6f, 0x62, 0x61, 0x72, 0x3a, 0x06, 0x9a, 0x82,
	0x19, 0x02, 0x08, 0x01, 0x22, 0x40, 0x0a, 0x10, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x4e, 0x65, 0x77, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6f, 0x6f, 0x62,
	0x61, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x06, 0x66, 0x6f, 0x6f, 0x62, 0x61, 0x72,
	0x3a, 0x14, 0x9a, 0x82, 0x19, 0x10, 0x1a, 0x0e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x22, 0x34, 0x0a, 0x0d, 0x54, 0x72, 0x69, 0x70, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x56, 0x34, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x64, 0x3a, 0x06, 0x9a, 0x82, 0x19, 0x02, 0x08, 0x01, 0x22, 0x45, 0x0a, 0x10,
	0x54, 0x72, 0x69, 0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x56, 0x32, 0x4e, 0x65, 0x77,
	0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x3a, 0x14, 0x9a,
	0x82, 0x19, 0x10, 0x08, 0x02, 0x1a, 0x0c, 0x74, 0x72, 0x69, 0x70, 0x5f, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x63, 0x68, 0x61, 0x63, 0x68, 0x6f, 0x2f, 0x68, 0x65,
	0x64, 0x77, 0x69, 0x67, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
}

var (
	file_protobuf_bad_proto_rawDescOnce sync.Once
	file_protobuf_bad_proto_rawDescData = file_protobuf_bad_proto_rawDesc
)

func file_protobuf_bad_proto_rawDescGZIP() []byte {
	file_protobuf_bad_proto_rawDescOnce.Do(func() {
		file_protobuf_bad_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_bad_proto_rawDescData)
	})
	return file_protobuf_bad_proto_rawDescData
}

var file_protobuf_bad_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protobuf_bad_proto_goTypes = []interface{}{
	(*DeviceCreated)(nil),    // 0: DeviceCreated
	(*DeviceCreatedNew)(nil), // 1: DeviceCreatedNew
	(*TripCreatedV4)(nil),    // 2: TripCreatedV4
	(*TripCreatedV2New)(nil), // 3: TripCreatedV2New
}
var file_protobuf_bad_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_bad_proto_init() }
func file_protobuf_bad_proto_init() {
	if File_protobuf_bad_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_bad_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceCreated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_bad_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceCreatedNew); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_bad_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TripCreatedV4); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_bad_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TripCreatedV2New); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_bad_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_bad_proto_goTypes,
		DependencyIndexes: file_protobuf_bad_proto_depIdxs,
		MessageInfos:      file_protobuf_bad_proto_msgTypes,
	}.Build()
	File_protobuf_bad_proto = out.File
	file_protobuf_bad_proto_rawDesc = nil
	file_protobuf_bad_proto_goTypes = nil
	file_protobuf_bad_proto_depIdxs = nil
}
