// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.3
// source: protobuf.proto

package internal

import (
	_ "github.com/cloudchacho/hedwig-go/protobuf"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TripCreatedV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VehicleId *string `protobuf:"bytes,1,req,name=vehicle_id,json=vehicleId" json:"vehicle_id,omitempty"`
	UserId    *string `protobuf:"bytes,2,req,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (x *TripCreatedV1) Reset() {
	*x = TripCreatedV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TripCreatedV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripCreatedV1) ProtoMessage() {}

func (x *TripCreatedV1) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripCreatedV1.ProtoReflect.Descriptor instead.
func (*TripCreatedV1) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{0}
}

func (x *TripCreatedV1) GetVehicleId() string {
	if x != nil && x.VehicleId != nil {
		return *x.VehicleId
	}
	return ""
}

func (x *TripCreatedV1) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

type TripCreatedV2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VehicleId *string `protobuf:"bytes,1,req,name=vehicle_id,json=vehicleId" json:"vehicle_id,omitempty"`
	Vin       *string `protobuf:"bytes,2,req,name=vin" json:"vin,omitempty"`
}

func (x *TripCreatedV2) Reset() {
	*x = TripCreatedV2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TripCreatedV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripCreatedV2) ProtoMessage() {}

func (x *TripCreatedV2) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripCreatedV2.ProtoReflect.Descriptor instead.
func (*TripCreatedV2) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{1}
}

func (x *TripCreatedV2) GetVehicleId() string {
	if x != nil && x.VehicleId != nil {
		return *x.VehicleId
	}
	return ""
}

func (x *TripCreatedV2) GetVin() string {
	if x != nil && x.Vin != nil {
		return *x.Vin
	}
	return ""
}

type DeviceCreatedV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId *string `protobuf:"bytes,1,req,name=device_id,json=deviceId" json:"device_id,omitempty"`
	UserId   *string `protobuf:"bytes,2,req,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (x *DeviceCreatedV1) Reset() {
	*x = DeviceCreatedV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceCreatedV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCreatedV1) ProtoMessage() {}

func (x *DeviceCreatedV1) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCreatedV1.ProtoReflect.Descriptor instead.
func (*DeviceCreatedV1) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceCreatedV1) GetDeviceId() string {
	if x != nil && x.DeviceId != nil {
		return *x.DeviceId
	}
	return ""
}

func (x *DeviceCreatedV1) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

type VehicleCreatedV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VehicleId *string `protobuf:"bytes,1,req,name=vehicle_id,json=vehicleId" json:"vehicle_id,omitempty"`
}

func (x *VehicleCreatedV1) Reset() {
	*x = VehicleCreatedV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VehicleCreatedV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleCreatedV1) ProtoMessage() {}

func (x *VehicleCreatedV1) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleCreatedV1.ProtoReflect.Descriptor instead.
func (*VehicleCreatedV1) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{3}
}

func (x *VehicleCreatedV1) GetVehicleId() string {
	if x != nil && x.VehicleId != nil {
		return *x.VehicleId
	}
	return ""
}

var File_protobuf_proto protoreflect.FileDescriptor

var file_protobuf_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1d, 0x68, 0x65, 0x64, 0x77, 0x69, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x67, 0x0a, 0x0d, 0x54, 0x72, 0x69, 0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x56, 0x31,
	0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x09, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x3a, 0x1e, 0x9a, 0x82, 0x19, 0x02, 0x08, 0x01,
	0x9a, 0x82, 0x19, 0x02, 0x10, 0x00, 0x9a, 0x82, 0x19, 0x0e, 0x1a, 0x0c, 0x74, 0x72, 0x69, 0x70,
	0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x22, 0x5a, 0x0a, 0x0d, 0x54, 0x72, 0x69, 0x70,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x56, 0x32, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x65, 0x68,
	0x69, 0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x09, 0x76,
	0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x69, 0x6e, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x03, 0x76, 0x69, 0x6e, 0x3a, 0x18, 0x9a, 0x82, 0x19, 0x02,
	0x08, 0x02, 0x9a, 0x82, 0x19, 0x0e, 0x1a, 0x0c, 0x74, 0x72, 0x69, 0x70, 0x5f, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x22, 0x63, 0x0a, 0x0f, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x56, 0x31, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x3a, 0x1a, 0x9a,
	0x82, 0x19, 0x02, 0x08, 0x01, 0x9a, 0x82, 0x19, 0x10, 0x1a, 0x0e, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x22, 0x4e, 0x0a, 0x10, 0x56, 0x65, 0x68,
	0x69, 0x63, 0x6c, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x56, 0x31, 0x12, 0x1d, 0x0a,
	0x0a, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x09, 0x52, 0x09, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x3a, 0x1b, 0x9a, 0x82,
	0x19, 0x02, 0x08, 0x01, 0x9a, 0x82, 0x19, 0x11, 0x1a, 0x0f, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c,
	0x65, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x63, 0x68, 0x61,
	0x63, 0x68, 0x6f, 0x2f, 0x68, 0x65, 0x64, 0x77, 0x69, 0x67, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
}

var (
	file_protobuf_proto_rawDescOnce sync.Once
	file_protobuf_proto_rawDescData = file_protobuf_proto_rawDesc
)

func file_protobuf_proto_rawDescGZIP() []byte {
	file_protobuf_proto_rawDescOnce.Do(func() {
		file_protobuf_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_proto_rawDescData)
	})
	return file_protobuf_proto_rawDescData
}

var file_protobuf_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protobuf_proto_goTypes = []interface{}{
	(*TripCreatedV1)(nil),    // 0: TripCreatedV1
	(*TripCreatedV2)(nil),    // 1: TripCreatedV2
	(*DeviceCreatedV1)(nil),  // 2: DeviceCreatedV1
	(*VehicleCreatedV1)(nil), // 3: VehicleCreatedV1
}
var file_protobuf_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_proto_init() }
func file_protobuf_proto_init() {
	if File_protobuf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TripCreatedV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TripCreatedV2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceCreatedV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VehicleCreatedV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_proto_goTypes,
		DependencyIndexes: file_protobuf_proto_depIdxs,
		MessageInfos:      file_protobuf_proto_msgTypes,
	}.Build()
	File_protobuf_proto = out.File
	file_protobuf_proto_rawDesc = nil
	file_protobuf_proto_goTypes = nil
	file_protobuf_proto_depIdxs = nil
}
