// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v5.29.5
// source: protobuf_alternate.proto

package internal

import (
	_ "github.com/cloudchacho/hedwig-go/protobuf"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// minor versioned
type TripCreatedV3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VehicleId *string `protobuf:"bytes,1,req,name=vehicle_id,json=vehicleId" json:"vehicle_id,omitempty"`
	UserId    *string `protobuf:"bytes,2,req,name=user_id,json=userId" json:"user_id,omitempty"`
	Vin       *string `protobuf:"bytes,3,req,name=vin" json:"vin,omitempty"`
}

func (x *TripCreatedV3) Reset() {
	*x = TripCreatedV3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_alternate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TripCreatedV3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripCreatedV3) ProtoMessage() {}

func (x *TripCreatedV3) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_alternate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripCreatedV3.ProtoReflect.Descriptor instead.
func (*TripCreatedV3) Descriptor() ([]byte, []int) {
	return file_protobuf_alternate_proto_rawDescGZIP(), []int{0}
}

func (x *TripCreatedV3) GetVehicleId() string {
	if x != nil && x.VehicleId != nil {
		return *x.VehicleId
	}
	return ""
}

func (x *TripCreatedV3) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *TripCreatedV3) GetVin() string {
	if x != nil && x.Vin != nil {
		return *x.Vin
	}
	return ""
}

// explicit message type
type TripCreatedNew struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VehicleId *string `protobuf:"bytes,1,req,name=vehicle_id,json=vehicleId" json:"vehicle_id,omitempty"`
	UserId    *string `protobuf:"bytes,2,req,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (x *TripCreatedNew) Reset() {
	*x = TripCreatedNew{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_alternate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TripCreatedNew) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripCreatedNew) ProtoMessage() {}

func (x *TripCreatedNew) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_alternate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripCreatedNew.ProtoReflect.Descriptor instead.
func (*TripCreatedNew) Descriptor() ([]byte, []int) {
	return file_protobuf_alternate_proto_rawDescGZIP(), []int{1}
}

func (x *TripCreatedNew) GetVehicleId() string {
	if x != nil && x.VehicleId != nil {
		return *x.VehicleId
	}
	return ""
}

func (x *TripCreatedNew) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

var File_protobuf_alternate_proto protoreflect.FileDescriptor

var file_protobuf_alternate_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x61, 0x6c, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x68, 0x65, 0x64, 0x77,
	0x69, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x63, 0x0a, 0x0d, 0x54, 0x72, 0x69,
	0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x56, 0x33, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x65,
	0x68, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x09,
	0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52,
	0x03, 0x76, 0x69, 0x6e, 0x3a, 0x08, 0x9a, 0x82, 0x19, 0x04, 0x08, 0x03, 0x10, 0x01, 0x22, 0x60,
	0x0a, 0x0e, 0x54, 0x72, 0x69, 0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x4e, 0x65, 0x77,
	0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x09, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x3a, 0x16, 0x9a, 0x82, 0x19, 0x12, 0x08, 0x04,
	0x10, 0x00, 0x1a, 0x0c, 0x74, 0x72, 0x69, 0x70, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x63, 0x68, 0x61, 0x63, 0x68, 0x6f, 0x2f, 0x68, 0x65, 0x64, 0x77, 0x69,
	0x67, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
}

var (
	file_protobuf_alternate_proto_rawDescOnce sync.Once
	file_protobuf_alternate_proto_rawDescData = file_protobuf_alternate_proto_rawDesc
)

func file_protobuf_alternate_proto_rawDescGZIP() []byte {
	file_protobuf_alternate_proto_rawDescOnce.Do(func() {
		file_protobuf_alternate_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_alternate_proto_rawDescData)
	})
	return file_protobuf_alternate_proto_rawDescData
}

var file_protobuf_alternate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_alternate_proto_goTypes = []interface{}{
	(*TripCreatedV3)(nil),  // 0: TripCreatedV3
	(*TripCreatedNew)(nil), // 1: TripCreatedNew
}
var file_protobuf_alternate_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_alternate_proto_init() }
func file_protobuf_alternate_proto_init() {
	if File_protobuf_alternate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_alternate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TripCreatedV3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_alternate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TripCreatedNew); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_alternate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_alternate_proto_goTypes,
		DependencyIndexes: file_protobuf_alternate_proto_depIdxs,
		MessageInfos:      file_protobuf_alternate_proto_msgTypes,
	}.Build()
	File_protobuf_alternate_proto = out.File
	file_protobuf_alternate_proto_rawDesc = nil
	file_protobuf_alternate_proto_goTypes = nil
	file_protobuf_alternate_proto_depIdxs = nil
}
