name: Golint

on:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - '.github/workflows/golangci-lint.yml'
  pull_request:
    paths:
      - '**.go'
      - '.github/workflows/golangci-lint.yml'

jobs:
  golangci:
    name: Format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ['1.23', '1.24']
    steps:
      - id: setup
        name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_version }}

      - id: checkout
        name: Checkout PR
        uses: actions/checkout@v4

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6
